[tool.black]
line-length = 88
target-version = ["py312"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_first_party = ["web_sniffer", "core", "scrapers"]
default_section = "THIRDPARTY"

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "I", "C", "N", "Q"]
ignore = ["E501"]  # ignore long lines if needed
exclude = ["venv", ".venv", "build", "dist"]

[tool.mypy]
python_version = 3.12
files = ["web_sniffer", "core", "scrapers"]
ignore_missing_imports = true
strict = true
